repos:
-   repo: https://github.com/JulienPalard/powrap
    rev: v1.0.0
    hooks:
    -   id: powrap
-   repo: local
    hooks:
    -   id: merge-dicts
        name: merge-dicts
        entry: python ./scripts/create_dict.py
        language: python
# This one requires package ``hunspell-es_es`` in Archlinux
-   repo: https://github.com/JulienPalard/pospell
    rev: v1.0.13
    hooks:
    -   id: pospell
        args: ['--personal-dict', 'dict.txt', '--modified', '--language', 'es_ES']
